### ISSUE TITLE
[REFACTOR] 로그인, 정원 컴포넌트 수정

### ISSUE THREAD

**Issue by seungboshim** [wantPlant/wantPlant_WFE#14]
### ✏️ 개요
ex) OOO 페이지 뷰 구현
> 로그인, 정원 컴포넌트 수정

### ✅ ToDo
ex) 헤더 구현, OOO 컴포넌트 구현, ...
-   [x] App.jsx에서 uri 설정
-   [x] 전체 레이아웃 통일
-   [ ] 컴포넌트화 가능한것 떼기
