### ISSUE TITLE
[FEAT] 정원 우측 컴포넌트 완성 및 더미데이터 작성

### ISSUE THREAD

**Issue by seungboshim** [wantPlant/wantPlant_WFE#28]
### ✏️ 개요
ex) OOO 페이지 뷰 구현
> 정원 우측 컴포넌트 완성, 더미데이터

### ✅ ToDo
ex) 헤더 구현, OOO 컴포넌트 구현, ...
-   [x] 화분생성시 색상 선택 효과
-   [x] 반응형 레이아웃 구현
-   [x] 투두 조회 컴포넌트 구현
-   [x] 더미데이터 작성
