### ISSUE TITLE
[TEST] 더미데이터 작성

### ISSUE THREAD

**Issue by seungboshim** [wantPlant/wantPlant_WFE#29]
### ✏️ 개요
ex) OOO 페이지 뷰 구현
> api 연동을 위한 더미데이터 작성

### ✅ ToDo
ex) 헤더 구현, OOO 컴포넌트 구현, ...
-   [ ] 정원 더미데이터 작성
-   [ ] 화분 더미데이터 작성
-   [ ] 투두 더미데이터 작성
