### ISSUE TITLE
[FEAT] 프로젝트 세팅 및 카카오 로그인

### ISSUE THREAD

**Issue by seungboshim** [wantPlant/wantPlant_WFE#4]
### ✏️ 개요
ex) OOO 페이지 뷰 구현
> 프로젝트 기본 세팅 및 카카오 로그인 구현

### ✅ ToDo
ex) 헤더 구현, OOO 컴포넌트 구현, ...
-   [x] 폴더 구조, 글로벌 스타일 설정
-   [x] 메인 레이아웃 설정
-   [x] 카카오 로그인 레이아웃 구현
-   [x] 로그인 구현 및 키 발급
-   [x] 리다이렉트 페이지
